### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tzt345** [9P9/Nitro-Generator#2]
```js
(node:28339) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
    at Object.connect (_tls_wrap.js:1619:15)
    at SocksProxyAgent.<anonymous> (/data/data/com.termux/files/home/GenNitro/node_modules/socks-proxy-agent/dist/agent.js:162:38)
    at Generator.next (<anonymous>)
    at fulfilled (/data/data/com.termux/files/home/GenNitro/node_modules/socks-proxy-agent/dist/agent.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Fix it plz

**Comment by tzt345** [comment]
Cuz idk

**Comment by tzt345** [comment]
& this too!

```js
(node:10861) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by tzt345** [comment]
@9P9

**Comment by 9P9** [comment]
Hi sorry for the long wait, error is now fixed :)
